"""
step11_transfer_matrix.py

Transfer matrix analysis: how does the velocity gradient tensor A map
to surface traction on an ellipsoid?

Because Stokes flow is linear, the traction vector tau at any surface
point x is a linear function of vec(A):

    tau(x) = M(x, r) @ vec(A)       shape: (3,) = (3, 9) @ (9,)

where M is the 3x9 traction transfer matrix, x is the surface point
in the BODY FRAME, and r = a/b is the aspect ratio.

This file computes and analyses M across:
  - Multiple surface points (tip, equator, off-axis)
  - Multiple aspect ratios

Key outputs
-----------
1. SVD of M at each surface point and aspect ratio
     - Singular values: how strongly each mode of A is amplified
     - Right singular vectors: which components of A drive traction
     - Left singular vectors: which traction directions are excited
2. Analytical traction covariance from CM empirical Cov(A)
     Cov(tau) = M @ Cov(vec(A)) @ M.T
   compared against the empirical traction covariance from the time series
3. Dominant amplification (largest singular value) vs aspect ratio curve
4. Comparison of analytical vs empirical traction variance
   — breakdown of agreement quantifies the contribution of orientation
     coupling (the nonlinear effect rotation has on body-frame A)

Outputs saved to ra_coupling_plots/step11_*.png

Usage
-----
Place alongside jeffery4.py, orientation.py, grad_u.csv.
Run after grad_u.csv has been generated by grad_u_model.py.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.linalg import svd
import os, sys

# ── CONFIG ─────────────────────────────────────────────────────
CSV_PATH     = "grad_u.csv"
AXES         = [2.0, 1.0, 1.0]
MU           = 1.0
BURN_IN      = 0.10
OUTDIR       = "ra_coupling_plots/"
JEFFERY_PATH = "."

# Aspect ratios to sweep for the amplification vs r curve
# r < 1 = oblate (disk-like), r = 1 = sphere, r > 1 = prolate (rod-like)
ASPECT_RATIOS = [0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0, 8.0]

# ── IMPORTS ────────────────────────────────────────────────────
sys.path.insert(0, JEFFERY_PATH)
from jeffery4    import Ellipsoid
from orientation import integrate_orientation
from fast_traction import build_transfer_matrix, fast_traction_vectors, fast_traction_magnitude

os.makedirs(OUTDIR, exist_ok=True)


# ─────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────

def load_csv(path):
    df       = pd.read_csv(path)
    times    = df['time'].values
    A_series = np.zeros((len(df), 3, 3))
    for i in range(3):
        for j in range(3):
            A_series[:, i, j] = df[f'A{i+1}{j+1}'].values
    print(f"  Loaded {len(times)} timesteps")
    return times, A_series


def burn(arr, frac):
    n = int(len(arr) * frac)
    return arr[n:]


def surface_points_body_frame(a):
    """
    Return a dict of named surface points in the body frame.
    These are the natural high-stress candidates by symmetry.

    Points included:
      tip_pos  : (a, 0, 0)   — positive tip of major axis
      tip_neg  : (-a, 0, 0)  — negative tip
      eq_b_pos : (0, b, 0)   — equator along b-axis
      eq_b_neg : (0, -b, 0)
      eq_c_pos : (0, 0, c)   — equator along c-axis
      eq_c_neg : (0, 0, -c)
      off_45   : point on surface at 45 degrees between a and b axes
    """
    a0, b0, c0 = a[0], a[1], a[2]

    # 45-degree point between a and b axes: solve x^2/a^2 + y^2/b^2 = 1
    # with x = y*a/b  =>  x = a/sqrt(2), y = b/sqrt(2)
    x45 = a0 / np.sqrt(2)
    y45 = b0 / np.sqrt(2)

    return {
        'tip $(a,0,0)$':       np.array([a0,  0.,  0.]),
        'tip $(-a,0,0)$':      np.array([-a0, 0.,  0.]),
        'equator $(0,b,0)$':   np.array([0.,  b0,  0.]),
        'equator $(0,0,c)$':   np.array([0.,  0.,  c0]),
        '45° $(a/\\sqrt{2}, b/\\sqrt{2}, 0)$':
                               np.array([x45, y45, 0.]),
    }


def outward_normal(x, a):
    """
    Outward unit normal to ellipsoid surface at point x.
    n_i = x_i / a_i^2,  normalised.
    """
    n = x / (a**2)
    return n / np.linalg.norm(n)


def traction_transfer_matrix(ell, x, a):
    """
    Compute the 3x9 traction transfer matrix M at surface point x.

    tau(x) = M @ vec(A)

    where vec(A) is the row-major flattening of the 3x3 velocity
    gradient tensor A, and tau is the tangential traction vector.

    Strategy: linearity of Stokes flow means we can probe each of the
    9 basis directions of A independently, compute the resulting traction,
    and assemble M column by column.

    Parameters
    ----------
    ell : Ellipsoid  (already in surface mode)
    x   : (3,) surface point in body frame
    a   : (3,) semi-axes

    Returns
    -------
    M : (3, 9) transfer matrix
    """
    x   = np.asarray(x, dtype=float)
    n   = outward_normal(x, a)
    M   = np.zeros((3, 9))

    for k in range(9):
        # Build basis A_k: 1 in position (k//3, k%3), 0 elsewhere
        A_basis        = np.zeros((3, 3))
        A_basis[k // 3, k % 3] = 1.0

        ell.set_strain(A_basis)
        ell.set_coefs()

        sig   = ell.sigma(x)          # (3, 3) stress tensor
        t_vec = sig @ n               # traction vector
        tau   = t_vec - np.dot(t_vec, n) * n   # tangential component

        M[:, k] = tau

    return M


def vec(A):
    """Row-major vectorisation of a 3x3 matrix. Shape (9,)."""
    return A.flatten()


# ─────────────────────────────────────────────────────────────
# STEP 11a — COMPUTE TRANSFER MATRICES AND SVD
# ─────────────────────────────────────────────────────────────

def compute_transfer_matrices(axes):
    """
    For each named surface point, compute M and its SVD.

    Returns dict: point_name -> {
        'M'      : (3, 9) transfer matrix,
        'U'      : (3, 3) left singular vectors,
        'sv'     : (3,)   singular values,
        'Vt'     : (9, 9) right singular vectors (rows),
        'x'      : (3,)   surface point,
        'n'      : (3,)   outward normal,
    }
    """
    a    = np.array(axes, dtype=float)
    eps0 = np.zeros((3, 3))
    ell  = Ellipsoid(a, eps0, mu=MU)
    ell.use_surface_mode()

    points  = surface_points_body_frame(a)
    results = {}

    for name, x in points.items():
        print(f"  Computing M at {name}...", end=" ", flush=True)
        M = traction_transfer_matrix(ell, x, a)

        # SVD: M = U @ diag(sv) @ Vt
        U, sv, Vt = svd(M, full_matrices=True)

        results[name] = {
            'M':  M,
            'U':  U,
            'sv': sv,
            'Vt': Vt,
            'x':  x,
            'n':  outward_normal(x, a),
        }
        print(f"singular values = {sv}")

    return results


# ─────────────────────────────────────────────────────────────
# STEP 11b — ANALYTICAL vs EMPIRICAL TRACTION COVARIANCE
# ─────────────────────────────────────────────────────────────

def compute_cov_A(A_series):
    """
    Empirical covariance of vec(A) from the time series.
    Returns (9, 9) matrix.
    """
    vecs = A_series.reshape(-1, 9)           # (T, 9)
    return np.cov(vecs.T)                    # (9, 9)


def analytical_traction_cov(M, cov_A):
    """
    Predicted traction covariance from linearity:
    Cov(tau) = M @ Cov(vec(A)) @ M.T   shape (3, 3)
    """
    return M @ cov_A @ M.T


def empirical_traction_series(A_series, R_history, axes, mu, x_body):
    """
    Compute traction at body-frame point x_body at every timestep,
    transforming A into the body frame each time.
    Full nonlinear result including orientation coupling.
    Uses fast_traction_vectors for speed — vectorised einsum over all T.
    """
    M, n_hat = build_transfer_matrix(axes, x_body, mu=mu)
    return fast_traction_vectors(M, n_hat, A_series, R_history)  # (T, 3)


def linear_traction_series(A_series, M):
    """
    Traction predicted by the LINEAR transfer matrix (no orientation coupling):
    tau_linear(t) = M @ vec(A_lab(t))

    This treats A as if the particle were always axis-aligned — it ignores
    the body-frame rotation entirely. The difference between this and the
    empirical series quantifies the contribution of orientation coupling.
    """
    vecs = A_series.reshape(-1, 9)    # (T, 9)
    return (M @ vecs.T).T             # (T, 3)


# ─────────────────────────────────────────────────────────────
# STEP 11c — AMPLIFICATION vs ASPECT RATIO
# ─────────────────────────────────────────────────────────────

def amplification_vs_aspect_ratio(aspect_ratios):
    sigma1_list = []
    sigma2_list = []
    sigma3_list = []

    for r in aspect_ratios:
        axes  = [float(r), 1.0, 1.0]
        x_tip = np.array([float(r), 0.0, 0.0])
        print(f"  r={r:.2f}  tip={x_tip}...", end=" ", flush=True)

        M, _ = build_transfer_matrix(axes, x_tip, mu=MU)
        M_norm = M /float(r)
        _, sv, _ = svd(M_norm, full_matrices=False)

        sigma1_list.append(sv[0])
        sigma2_list.append(sv[1] if len(sv) > 1 else 0.0)
        sigma3_list.append(sv[2] if len(sv) > 2 else 0.0)
        print(f"sv = {sv}")

    return (np.array(aspect_ratios),
            np.array(sigma1_list),
            np.array(sigma2_list),
            np.array(sigma3_list))

# ─────────────────────────────────────────────────────────────
# PLOTTING
# ─────────────────────────────────────────────────────────────

def plot_svd_overview(svd_results, axes):
    """
    For each surface point, show:
      - Singular values (bar chart)
      - Dominant right singular vector v1 as a 3x3 heatmap
        (shows which A_ij components drive traction most)
      - Dominant left singular vector u1
        (shows the traction direction that is most excited)
    """
    points  = list(svd_results.keys())
    n_pts   = len(points)

    fig, axes_arr = plt.subplots(n_pts, 3,
                                  figsize=(15, 4 * n_pts))
    if n_pts == 1:
        axes_arr = axes_arr[np.newaxis, :]

    comp_labels = [f'$A_{{{i+1}{j+1}}}$'
                   for i in range(3) for j in range(3)]

    for row, name in enumerate(points):
        d  = svd_results[name]
        sv = d['sv']
        U  = d['U']
        Vt = d['Vt']

        # ── Col 0: singular values ────────────────────────────
        ax = axes_arr[row, 0]
        ax.bar(range(len(sv)), sv,
               color=['#E07B39', '#4472C4', '#5FAD56'],
               edgecolor='black', linewidth=0.8)
        ax.set_xticks(range(len(sv)))
        ax.set_xticklabels([f'$\\sigma_{k+1}$' for k in range(len(sv))],
                           fontsize=11)
        ax.set_ylabel('Singular value', fontsize=10)
        ax.set_title(f'{name}\nSingular values', fontsize=10,
                     fontweight='bold')
        ax.grid(True, alpha=0.3, axis='y')

        # Annotate ratio sigma2/sigma1
        if sv[0] > 1e-12:
            ax.text(0.98, 0.95,
                    f'$\\sigma_2/\\sigma_1 = {sv[1]/sv[0]:.3f}$',
                    transform=ax.transAxes, ha='right', va='top',
                    fontsize=9,
                    bbox=dict(boxstyle='round', facecolor='wheat',
                              alpha=0.5))

        # ── Col 1: dominant right sv (which A_ij drives traction) ─
        ax = axes_arr[row, 1]
        v1 = Vt[0].reshape(3, 3)   # first right singular vector as matrix
        im = ax.imshow(v1, cmap='RdBu_r', vmin=-1, vmax=1,
                       aspect='auto')
        ax.set_xticks(range(3)); ax.set_yticks(range(3))
        ax.set_xticklabels(['$j=1$', '$j=2$', '$j=3$'], fontsize=9)
        ax.set_yticklabels(['$i=1$', '$i=2$', '$i=3$'], fontsize=9)
        for ii in range(3):
            for jj in range(3):
                ax.text(jj, ii, f'{v1[ii, jj]:.2f}',
                        ha='center', va='center', fontsize=8,
                        color='black' if abs(v1[ii, jj]) < 0.6 else 'white')
        plt.colorbar(im, ax=ax, shrink=0.8)
        ax.set_title(f'Dominant right s.v. $\\mathbf{{v}}_1$\n'
                     f'(which $A_{{ij}}$ drives traction)',
                     fontsize=10, fontweight='bold')

        # ── Col 2: dominant left sv (traction direction excited) ──
        ax = axes_arr[row, 2]
        u1 = U[:, 0]   # first left singular vector, shape (3,)
        ax.bar(['$\\tau_x$', '$\\tau_y$', '$\\tau_z$'], u1,
               color=['#E07B39', '#4472C4', '#5FAD56'],
               edgecolor='black', linewidth=0.8)
        ax.axhline(0, color='grey', lw=0.8)
        ax.set_ylabel('Component', fontsize=10)
        ax.set_title(f'Dominant left s.v. $\\mathbf{{u}}_1$\n'
                     f'(traction direction excited by $\\mathbf{{v}}_1$)',
                     fontsize=10, fontweight='bold')
        ax.grid(True, alpha=0.3, axis='y')

        # Annotate surface point coordinates
        x_str = ', '.join(f'{xi:.2f}' for xi in d['x'])
        axes_arr[row, 0].set_xlabel(f'x = ({x_str})', fontsize=9)

    fig.suptitle(
        'SVD of traction transfer matrix $M$: '
        '$\\tau = M\\,\\mathrm{vec}(A)$\n'
        'Singular values = amplification of A into surface traction.  '
        '$\\mathbf{v}_1$ = most dangerous A-mode.  '
        '$\\mathbf{u}_1$ = traction direction excited.',
        fontsize=12, fontweight='bold'
    )
    fig.tight_layout()
    fig.savefig(OUTDIR + 'step11a_svd_overview.png',
                dpi=150, bbox_inches='tight')
    plt.close(fig)
    print("Saved step11a_svd_overview.png")


def plot_cov_comparison(name, M, cov_A, tau_empirical, tau_linear):
    """
    For one surface point, compare:
      - Analytical Cov(tau) = M Cov(A) M^T  (linear prediction, lab-frame A)
      - Empirical Cov(tau) from body-frame time series  (full nonlinear)
      - Empirical Cov(tau) from linear prediction time series

    Also plot variance of ||tau|| for all three.
    """
    cov_analytical = analytical_traction_cov(M, cov_A)
    cov_empirical  = np.cov(tau_empirical.T)
    cov_linear     = np.cov(tau_linear.T)

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    vmax = max(np.abs(cov_analytical).max(),
               np.abs(cov_empirical).max(),
               np.abs(cov_linear).max())

    titles = [
        'Analytical\n$M\\,\\mathrm{Cov}(A)\\,M^T$ (lab-frame A, no rotation)',
        'Empirical\n(body-frame A, full orientation coupling)',
        'Linear prediction\n($M\\,\\mathrm{vec}(A_{\\mathrm{lab}})$, no body frame)',
    ]
    mats = [cov_analytical, cov_empirical, cov_linear]

    for ax, mat, title in zip(axes, mats, titles):
        im = ax.imshow(mat, cmap='RdBu_r', vmin=-vmax, vmax=vmax)
        ax.set_xticks([0, 1, 2])
        ax.set_yticks([0, 1, 2])
        ax.set_xticklabels(['$\\tau_x$', '$\\tau_y$', '$\\tau_z$'])
        ax.set_yticklabels(['$\\tau_x$', '$\\tau_y$', '$\\tau_z$'])
        for ii in range(3):
            for jj in range(3):
                ax.text(jj, ii, f'{mat[ii, jj]:.3f}',
                        ha='center', va='center', fontsize=9,
                        color='black' if abs(mat[ii, jj]) < 0.6*vmax
                        else 'white')
        plt.colorbar(im, ax=ax, shrink=0.8)
        ax.set_title(title, fontsize=10, fontweight='bold')

    # Compute relative error between analytical and empirical
    diag_anal = np.diag(cov_analytical)
    diag_emp  = np.diag(cov_empirical)
    rel_err   = np.abs(diag_anal - diag_emp) / (np.abs(diag_emp) + 1e-30)

    fig.suptitle(
        f'Traction covariance: analytical vs empirical\n'
        f'Point: {name}\n'
        f'Relative error on diagonal (orientation coupling effect): '
        f'{rel_err[0]:.3f}, {rel_err[1]:.3f}, {rel_err[2]:.3f}',
        fontsize=11, fontweight='bold'
    )
    fig.tight_layout()
    safe_name = name.replace('$', '').replace('/', '_').replace(
        ' ', '_').replace('\\', '').replace(',', '')[:30]
    fname = OUTDIR + f'step11b_cov_{safe_name}.png'
    fig.savefig(fname, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved {fname}")

    return {
        'cov_analytical': cov_analytical,
        'cov_empirical':  cov_empirical,
        'cov_linear':     cov_linear,
        'rel_err_diag':   rel_err,
    }


def plot_variance_comparison_summary(cov_results, axes_label):
    """
    Bar chart comparing Var(||tau||) across surface points for all three
    covariance estimates — clean summary figure.
    """
    points        = list(cov_results.keys())
    var_anal      = [np.trace(cov_results[p]['cov_analytical']) for p in points]
    var_emp       = [np.trace(cov_results[p]['cov_empirical'])  for p in points]
    var_lin       = [np.trace(cov_results[p]['cov_linear'])     for p in points]
    rel_err       = [np.mean(cov_results[p]['rel_err_diag'])    for p in points]

    x    = np.arange(len(points))
    w    = 0.25

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    ax = axes[0]
    ax.bar(x - w,   var_anal, w, label='Analytical (no rotation)',
           color='#5FAD56', edgecolor='black', lw=0.8)
    ax.bar(x,       var_emp,  w, label='Empirical (full coupling)',
           color='#E07B39', edgecolor='black', lw=0.8)
    ax.bar(x + w,   var_lin,  w, label='Linear (lab-frame A)',
           color='#4472C4', edgecolor='black', lw=0.8, alpha=0.7)
    ax.set_xticks(x)
    ax.set_xticklabels(
        [p.replace('$', '').replace('\\sqrt{2}', '√2') for p in points],
        fontsize=8, rotation=15, ha='right')
    ax.set_ylabel('$\\mathrm{Tr}(\\mathrm{Cov}(\\tau))$ — total traction variance',
                  fontsize=10)
    ax.set_title('Total traction variance across surface points',
                 fontsize=11, fontweight='bold')
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3, axis='y')

    ax = axes[1]
    ax.bar(x, rel_err, color='crimson', edgecolor='black', lw=0.8, alpha=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels(
        [p.replace('$', '').replace('\\sqrt{2}', '√2') for p in points],
        fontsize=8, rotation=15, ha='right')
    ax.set_ylabel('Mean relative error (analytical vs empirical)',
                  fontsize=10)
    ax.set_title('Orientation coupling effect\n'
                 '(how much rotation changes traction statistics)',
                 fontsize=11, fontweight='bold')
    ax.grid(True, alpha=0.3, axis='y')
    ax.axhline(0.1, color='grey', lw=1.0, linestyle='--',
               label='10% threshold')
    ax.legend(fontsize=9)

    fig.suptitle(
        f'Traction variance: analytical prediction vs empirical\n'
        f'Axes: {axes_label}   '
        f'Gap = effect of orientation coupling on traction statistics',
        fontsize=12, fontweight='bold'
    )
    fig.tight_layout()
    fig.savefig(OUTDIR + 'step11b_variance_summary.png',
                dpi=150, bbox_inches='tight')
    plt.close(fig)
    print("Saved step11b_variance_summary.png")


def plot_amplification_vs_r(rs, sv1, sv2, sv3):
    """
    Dominant singular value of M at the tip vs aspect ratio.
    Shows how efficiently A is converted into surface traction
    as a function of particle shape.
    """
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # ── Left: all singular values ──────────────────────────────
    ax = axes[0]
    ax.plot(rs, sv1, 'o-', color='#E07B39', lw=2.5, ms=7,
            label='$\\sigma_1$ (dominant)')
    ax.plot(rs, sv2, 's--', color='#4472C4', lw=2.0, ms=6,
            label='$\\sigma_2$')
    ax.plot(rs, sv3, '^:', color='#5FAD56', lw=1.8, ms=6,
            label='$\\sigma_3$')
    ax.axvline(1.0, color='grey', lw=0.8, linestyle=':',
               label='sphere ($r=1$)')
    ax.set_xlabel('Aspect ratio $r = a/b$', fontsize=12)
    ax.set_ylabel('Singular value of $M/r$', fontsize=12)
    ax.set_title('Traction amplification vs aspect ratio\n'
                 '(evaluated at tip $(a,0,0)$)',
                 fontsize=11, fontweight='bold')
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.set_xscale('log')
    ax.text(0.3, ax.get_ylim()[1]*0.92, 'Oblate\n(disk)',
            ha='center', fontsize=9, color='grey')
    ax.text(3.0, ax.get_ylim()[1]*0.92, 'Prolate\n(rod)',
            ha='center', fontsize=9, color='grey')

    # ── Right: sigma1 normalised by sphere value ───────────────
    ax = axes[1]
    sphere_idx = np.argmin(np.abs(np.array(rs) - 1.0))
    sv1_norm   = sv1 / sv1[sphere_idx]
    ax.plot(rs, sv1_norm, 'o-', color='#E07B39', lw=2.5, ms=7)
    ax.axvline(1.0, color='grey', lw=0.8, linestyle=':')
    ax.axhline(1.0, color='grey', lw=0.8, linestyle='--',
               label='sphere baseline')
    ax.set_xlabel('Aspect ratio $r = a/b$', fontsize=12)
    ax.set_ylabel('$\\sigma_1(r) / \\sigma_1(r=1)$', fontsize=12)
    ax.set_title('Relative amplification vs sphere\n'
                 '(how much more/less efficiently A drives traction)',
                 fontsize=11, fontweight='bold')
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.set_xscale('log')

    fig.suptitle(
        'Dominant singular value of traction transfer matrix $M/r$ vs aspect ratio\n'
        '$\\sigma_1 = \\max_{\\|\\mathrm{vec}(A)\\|=1} \\|\\tau\\|$ '
        '— maximum traction produced by unit-norm velocity gradient',
        fontsize=12, fontweight='bold'
    )
    fig.tight_layout()
    fig.savefig(OUTDIR + 'step11c_amplification_vs_r.png',
                dpi=150, bbox_inches='tight')
    plt.close(fig)
    print("Saved step11c_amplification_vs_r.png")


def plot_right_sv_vs_r(aspect_ratios):
    """
    Show how the dominant right singular vector (most dangerous A mode)
    changes with aspect ratio. Plotted as a heatmap: rows = r values,
    columns = A_ij components.
    """
    comp_labels = [f'$A_{{{i+1}{j+1}}}$'
                   for i in range(3) for j in range(3)]
    v1_matrix = []

    for r in aspect_ratios:
        axes  = [float(r), 1.0, 1.0]
        x_tip = np.array([float(r), 0.0, 0.0])
        M, _  = build_transfer_matrix(axes, x_tip, mu=MU)
        M_norm = M /float(r)
        _, sv, Vt = svd(M_norm, full_matrices=False)
        # Sign convention: make largest-magnitude component positive
        v1 = Vt[0]
        if v1[np.argmax(np.abs(v1))] < 0:
            v1 = -v1
        v1_matrix.append(v1)

    v1_matrix = np.array(v1_matrix)   # (n_r, 9)

    fig, ax = plt.subplots(figsize=(12, 6))
    im = ax.imshow(v1_matrix.T, aspect='auto', cmap='RdBu_r',
                   vmin=-1, vmax=1,
                   extent=[-0.5, len(aspect_ratios)-0.5, -0.5, 8.5])
    ax.set_yticks(range(9))
    ax.set_yticklabels(comp_labels[::-1], fontsize=10)
    ax.set_xticks(range(len(aspect_ratios)))
    ax.set_xticklabels([f'{r}' for r in aspect_ratios],
                       fontsize=9, rotation=45, ha='right')
    ax.set_xlabel('Aspect ratio $r = a/b$', fontsize=12)
    ax.set_ylabel('$A_{ij}$ component', fontsize=12)
    ax.set_title(
        'Dominant right singular vector $\\mathbf{v}_1(r)$ vs aspect ratio\n'
        'Shows which $A_{ij}$ component most efficiently drives traction '
        'as particle shape changes',
        fontsize=11, fontweight='bold'
    )
    plt.colorbar(im, ax=ax, label='Component value')
    fig.tight_layout()
    fig.savefig(OUTDIR + 'step11c_right_sv_vs_r.png',
                dpi=150, bbox_inches='tight')
    plt.close(fig)
    print("Saved step11c_right_sv_vs_r.png")


def plot_traction_timeseries_comparison(times, tau_empirical,
                                        tau_linear, name):
    """
    Time series comparison of ||tau|| from empirical (full coupling)
    vs linear (M @ vec(A_lab)) prediction.
    Shows where and when orientation coupling matters most.
    """
    mag_emp = np.linalg.norm(tau_empirical, axis=1)
    mag_lin = np.linalg.norm(tau_linear,    axis=1)
    diff    = mag_emp - mag_lin

    fig, axes = plt.subplots(3, 1, figsize=(14, 9), sharex=True)

    axes[0].plot(times, mag_emp, lw=0.8, color='#E07B39',
                 label='Empirical (body-frame, full coupling)')
    axes[0].plot(times, mag_lin, lw=0.8, color='#4472C4',
                 alpha=0.7, label='Linear ($M\\,\\mathrm{vec}(A_{lab})$)')
    axes[0].set_ylabel('$\\|\\tau\\|$', fontsize=11)
    axes[0].set_title(f'Traction magnitude: point {name}',
                      fontsize=11, fontweight='bold')
    axes[0].legend(fontsize=9)
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(times, diff, lw=0.8, color='crimson', alpha=0.8)
    axes[1].axhline(0, color='grey', lw=0.8)
    axes[1].set_ylabel('Empirical $-$ Linear', fontsize=11)
    axes[1].set_title('Difference (orientation coupling contribution)',
                      fontsize=11, fontweight='bold')
    axes[1].grid(True, alpha=0.3)

    # Rolling std of difference as a proxy for coupling strength over time
    window = max(1, len(diff) // 100)
    roll_std = pd.Series(diff).rolling(window, center=True).std().values
    axes[2].plot(times, roll_std, lw=1.0, color='purple')
    axes[2].set_ylabel('Rolling std of difference', fontsize=11)
    axes[2].set_xlabel('Time ($\\tau_\\eta$)', fontsize=11)
    axes[2].set_title(f'Local coupling strength '
                      f'(rolling window = {window} steps)',
                      fontsize=11, fontweight='bold')
    axes[2].grid(True, alpha=0.3)

    fig.suptitle(
        f'Linear vs full traction: point {name}\n'
        f'Pearson r = {np.corrcoef(mag_emp, mag_lin)[0,1]:.4f}   '
        f'Mean |diff| = {np.mean(np.abs(diff)):.4f}   '
        f'RMS diff = {np.sqrt(np.mean(diff**2)):.4f}',
        fontsize=11, fontweight='bold'
    )
    fig.tight_layout()
    safe_name = name.replace('$', '').replace('/', '_').replace(
        ' ', '_').replace('\\', '').replace(',', '')[:30]
    fname = OUTDIR + f'step11b_timeseries_{safe_name}.png'
    fig.savefig(fname, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved {fname}")


# ─────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────

if __name__ == '__main__':

    import pandas as pd   # needed for rolling std in timeseries plot

    print("── Step 11: Transfer Matrix Analysis ──\n")

    # ── Load and prep data ──────────────────────────────────────
    print("Loading CM data...")
    times, A_series = load_csv(CSV_PATH)
    n_burn  = int(len(times) * BURN_IN)
    times_b = times[n_burn:]
    A_b     = A_series[n_burn:]

    # ── Integrate orientation ───────────────────────────────────
    print("\nIntegrating orientation ODE...")
    R_history, *_ = integrate_orientation(AXES, A_series, times)
    R_b = R_history[n_burn:]

    # ── 11a: SVD of M at each surface point ────────────────────
    print("\n── 11a: SVD of transfer matrix at surface points ──")
    svd_results = compute_transfer_matrices(AXES)
    plot_svd_overview(svd_results, AXES)

    # ── 11b: Analytical vs empirical traction covariance ───────
    print("\n── 11b: Analytical vs empirical traction covariance ──")
    cov_A = compute_cov_A(A_b)
    print(f"  Cov(vec(A)) shape: {cov_A.shape}")

    a         = np.array(AXES, dtype=float)
    points    = surface_points_body_frame(a)
    cov_results = {}

    for name, x_body in points.items():
        print(f"\n  Point: {name}")
        M = svd_results[name]['M']

        print("    Computing empirical traction time series (body frame, fast)...")
        # fast_traction_vectors rotates A into body frame then applies M —
        # same result as old empirical_traction_series but vectorised
        tau_emp = fast_traction_vectors(M, svd_results[name]['n'], A_b, R_b)

        print("    Computing linear traction time series (lab frame A)...")
        tau_lin = linear_traction_series(A_b, M)

        cov_r = plot_cov_comparison(name, M, cov_A, tau_emp, tau_lin)
        cov_results[name] = cov_r

        plot_traction_timeseries_comparison(times_b, tau_emp,
                                             tau_lin, name)

    plot_variance_comparison_summary(cov_results, str(AXES))

    # ── 11c: Amplification vs aspect ratio ─────────────────────
    print("\n── 11c: Dominant singular value vs aspect ratio ──")
    rs, sv1, sv2, sv3 = amplification_vs_aspect_ratio(ASPECT_RATIOS)
    plot_amplification_vs_r(rs, sv1, sv2, sv3)

    print("\n── 11c: Dominant right singular vector vs aspect ratio ──")
    plot_right_sv_vs_r(ASPECT_RATIOS)

    print(f"\nAll step 11 plots saved to '{OUTDIR}'")
    print("Done.")